### ISSUE TITLE
NOT Support win path

### ISSUE THREAD

**Issue by xjspace** [webarx-security/wpbullet#5]
F:\wpbullet>python wpbullet.py --path="F:\wpen"
raceback (most recent call last):

  File "wpbullet.py", line 2, in <module>
    from core import scanner
  File "F:\wpbullet\core\scanner.py", line 52
    print('Checked files: ' + str(count_files), end="\r")
                                                   ^
SyntaxError: invalid syntax

**Comment by LukaSikic** [comment]
Please make sure you are using Python 3
